# Generated by Django 3.1.7 on 2021-09-23 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_auto_20210806_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='to_predict',
            field=models.BooleanField(default=False),
        ),
    ]
